In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=["id", "Unnamed: 32"],inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:,0], test_size=0.2)

# Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.47140879, -0.1736801 , -0.50632195, ..., -0.450064  ,
         0.1320471 , -0.68392654],
       [ 0.51834484,  0.22699535,  0.49131755, ...,  0.52775996,
         1.80701045,  1.17846875],
       [ 0.50374671,  0.24105414,  0.43211046, ...,  0.62326262,
         0.88495142,  0.09553036],
       ...,
       [-0.5152032 , -0.29552293, -0.5359255 , ..., -0.39045186,
         0.5217663 , -0.53029915],
       [-0.07141986,  0.77997434,  0.11070053, ...,  1.65068635,
         1.14863377,  3.15675839],
       [-1.23897879, -0.92348212, -1.15041053, ...,  0.66947358,
         0.33934455,  2.22960357]])

In [ ]:
y_train

107    B
223    M
182    M
37     B
330    M
      ..
557    B
520    B
367    B
14     M
152    B
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0])

# Numpy array to PyTorch Tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)
X_test_tensor = torch.from_numpy(X_test)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[-0.4714, -0.1737, -0.5063,  ..., -0.4501,  0.1320, -0.6839],
        [ 0.5183,  0.2270,  0.4913,  ...,  0.5278,  1.8070,  1.1785],
        [ 0.5037,  0.2411,  0.4321,  ...,  0.6233,  0.8850,  0.0955],
        ...,
        [-0.5152, -0.2955, -0.5359,  ..., -0.3905,  0.5218, -0.5303],
        [-0.0714,  0.7800,  0.1107,  ...,  1.6507,  1.1486,  3.1568],
        [-1.2390, -0.9235, -1.1504,  ...,  0.6695,  0.3393,  2.2296]],
       dtype=torch.float64)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

# Defining the Model

In [ ]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_fn(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

# Important parameters for training Neural network

In [ ]:
learning_rate = 0.1 # used for optimizing gradients
epochs = 25 # represents no. of turns done on data

# Training Pipeline

In [ ]:
# creating model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss
  loss = model.loss_fn(y_pred,y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.6125452963276055
Epoch: 2, Loss: 3.494928321954934
Epoch: 3, Loss: 3.3714799833965023
Epoch: 4, Loss: 3.2408336771167794
Epoch: 5, Loss: 3.099858621293846
Epoch: 6, Loss: 2.9565883743538226
Epoch: 7, Loss: 2.81224745947419
Epoch: 8, Loss: 2.661651727216423
Epoch: 9, Loss: 2.501345679245629
Epoch: 10, Loss: 2.3358926164978806
Epoch: 11, Loss: 2.1678642462332536
Epoch: 12, Loss: 2.0028328943293316
Epoch: 13, Loss: 1.8441709702760651
Epoch: 14, Loss: 1.6911334197871466
Epoch: 15, Loss: 1.5432179652149494
Epoch: 16, Loss: 1.398815299413434
Epoch: 17, Loss: 1.268237605998919
Epoch: 18, Loss: 1.1534201006544555
Epoch: 19, Loss: 1.0559087692762124
Epoch: 20, Loss: 0.976446735298969
Epoch: 21, Loss: 0.9145593766641964
Epoch: 22, Loss: 0.8683805880302617
Epoch: 23, Loss: 0.8349734018899433
Epoch: 24, Loss: 0.811067354797022
Epoch: 25, Loss: 0.79376027882298

In [ ]:
model.weights

tensor([[ 0.2029],
        [ 0.0588],
        [-0.1580],
        [ 0.1898],
        [-0.2232],
        [ 0.3564],
        [-0.5157],
        [ 0.1908],
        [-0.1937],
        [ 0.5655],
        [-0.0672],
        [-0.1295],
        [-0.3640],
        [ 0.5357],
        [ 0.5389],
        [ 0.2032],
        [ 0.1235],
        [ 0.4120],
        [-0.0666],
        [-0.2203],
        [ 0.1521],
        [ 0.5868],
        [-0.4901],
        [ 0.1900],
        [ 0.3788],
        [-0.1211],
        [-0.3385],
        [-0.1728],
        [ 0.3453],
        [-0.4296]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1659], dtype=torch.float64, requires_grad=True)

# Evaluate

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred =(y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5846414566040039