In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from torch import nn

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [ ]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [ ]:
train_dataset[10]

(tensor([ 3.9483, -0.1928,  3.9586,  5.2164,  1.2568,  0.9384,  2.9562,  2.8783,
         -0.6233, -1.0783,  8.8121,  0.4587,  9.3367, 10.2972,  2.2969,  0.1446,
          1.0355,  0.3797,  3.1675,  0.2436,  2.4313, -1.1741,  2.4058,  2.8156,
         -0.8157, -0.6572,  0.2370,  0.6932, -1.9738, -1.6451],
        dtype=torch.float64),
 tensor(1))

In [ ]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# Ensure input and target tensors are float32 to match model weights
X_train_tensor_f32 = X_train_tensor.float()
y_train_tensor_f32 = y_train_tensor.float()

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# define loop
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader: # New code

    # forward pass
    y_pred = model(batch_features.float())

    # loss calculate
    loss = loss_function(y_pred, batch_labels.float().view(-1,1))

    # zero gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # manual way of optimizing gradients
    # parameters update
      #with torch.no_grad():
        #model.linear.weight -= learning_rate * model.linear.weight.grad
        #model.linear.bias -= learning_rate * model.linear.bias.grad
    # making the value of gradients zero becoz it gets accumulated after every epoch
      # zero gradients
        # model.linear.weight.grad.zero_()
        # model.linear.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.8986955881118774
Epoch: 1, Loss: 0.6470350027084351
Epoch: 1, Loss: 0.4525948166847229
Epoch: 1, Loss: 0.38566288352012634
Epoch: 1, Loss: 0.41623756289482117
Epoch: 1, Loss: 0.34193918108940125
Epoch: 1, Loss: 0.33018410205841064
Epoch: 1, Loss: 0.2810809016227722
Epoch: 1, Loss: 0.24642477929592133
Epoch: 1, Loss: 0.2678336203098297
Epoch: 1, Loss: 0.30362898111343384
Epoch: 1, Loss: 0.31511831283569336
Epoch: 1, Loss: 0.22301334142684937
Epoch: 1, Loss: 0.2664147913455963
Epoch: 1, Loss: 0.27379822731018066
Epoch: 2, Loss: 0.17407067120075226
Epoch: 2, Loss: 0.2434849739074707
Epoch: 2, Loss: 0.22027631103992462
Epoch: 2, Loss: 0.15776598453521729
Epoch: 2, Loss: 0.13242687284946442
Epoch: 2, Loss: 0.2596694827079773
Epoch: 2, Loss: 0.1838100105524063
Epoch: 2, Loss: 0.26243844628334045
Epoch: 2, Loss: 0.16682395339012146
Epoch: 2, Loss: 0.2097126990556717
Epoch: 2, Loss: 0.22774749994277954
Epoch: 2, Loss: 0.1960890293121338
Epoch: 2, Loss: 0.162048801779747
Epoch: 2, Loss: 0.137050598859787
Epoch: 2, Loss: 0.08972389996051788
Epoch: 3, Loss: 0.29009386897087097
Epoch: 3, Loss: 0.13122491538524628
Epoch: 3, Loss: 0.19474203884601593
Epoch: 3, Loss: 0.05952416732907295
Epoch: 3, Loss: 0.2322634756565094
Epoch: 3, Loss: 0.13715669512748718
Epoch: 3, Loss: 0.16873590648174286
Epoch: 3, Loss: 0.17453989386558533
Epoch: 3, Loss: 0.06892658025026321
Epoch: 3, Loss: 0.12484738975763321
Epoch: 3, Loss: 0.16963227093219757
Epoch: 3, Loss: 0.13862185180187225
Epoch: 3, Loss: 0.1704522669315338
Epoch: 3, Loss: 0.1605122834444046
Epoch: 3, Loss: 0.044579554349184036
Epoch: 4, Loss: 0.24295441806316376
Epoch: 4, Loss: 0.1302947849035263
Epoch: 4, Loss: 0.14676529169082642
Epoch: 4, Loss: 0.14816482365131378
Epoch: 4, Loss: 0.21946243941783905
Epoch: 4, Loss: 0.11088303476572037
Epoch: 4, Loss: 0.1037055253982544
Epoch: 4, Loss: 0.11210253834724426
Epoch: 4, Loss: 0.172527015209198
Epoch: 4, Loss: 0.17197510600090027
Epoch: 4, Loss: 0.10447751730680466
Epoch: 4, Loss: 0.11402536928653717
Epoch: 4, Loss: 0.06412756443023682
Epoch: 4, Loss: 0.08243975043296814
Epoch: 4, Loss: 0.15902173519134521
Epoch: 5, Loss: 0.1486990600824356
Epoch: 5, Loss: 0.11324354261159897
Epoch: 5, Loss: 0.15054066479206085
Epoch: 5, Loss: 0.06485845893621445
Epoch: 5, Loss: 0.16447827219963074
Epoch: 5, Loss: 0.07285822927951813
Epoch: 5, Loss: 0.18092882633209229
Epoch: 5, Loss: 0.1473342329263687
Epoch: 5, Loss: 0.07823514938354492
Epoch: 5, Loss: 0.1880962997674942
Epoch: 5, Loss: 0.1020147055387497
Epoch: 5, Loss: 0.07329973578453064
Epoch: 5, Loss: 0.1080603376030922
Epoch: 5, Loss: 0.14843527972698212
Epoch: 5, Loss: 0.2402905374765396
Epoch: 6, Loss: 0.17743074893951416
Epoch: 6, Loss: 0.23871749639511108
Epoch: 6, Loss: 0.07588880509138107
Epoch: 6, Loss: 0.12790411710739136
Epoch: 6, Loss: 0.1123405396938324
Epoch: 6, Loss: 0.12837441265583038
Epoch: 6, Loss: 0.08438115566968918
Epoch: 6, Loss: 0.09522304683923721
Epoch: 6, Loss: 0.0690603107213974
Epoch: 6, Loss: 0.10734860599040985
Epoch: 6, Loss: 0.11240245401859283
Epoch: 6, Loss: 0.10408283025026321
Epoch: 6, Loss: 0.11739862710237503
Epoch: 6, Loss: 0.09925815463066101
Epoch: 6, Loss: 0.09016694873571396
Epoch: 7, Loss: 0.12267068028450012
Epoch: 7, Loss: 0.15360119938850403
Epoch: 7, Loss: 0.06211952865123749
Epoch: 7, Loss: 0.06622140854597092
Epoch: 7, Loss: 0.08581801503896713
Epoch: 7, Loss: 0.10183246433734894
Epoch: 7, Loss: 0.06843996047973633
Epoch: 7, Loss: 0.03003356233239174
Epoch: 7, Loss: 0.15354277193546295
Epoch: 7, Loss: 0.20751988887786865
Epoch: 7, Loss: 0.10084272176027298
Epoch: 7, Loss: 0.10200046747922897
Epoch: 7, Loss: 0.1853577345609665
Epoch: 7, Loss: 0.13939957320690155
Epoch: 7, Loss: 0.013850134797394276
Epoch: 8, Loss: 0.08487778902053833
Epoch: 8, Loss: 0.058126050978899
Epoch: 8, Loss: 0.1042608991265297
Epoch: 8, Loss: 0.09741129726171494
Epoch: 8, Loss: 0.13719356060028076
Epoch: 8, Loss: 0.06154652312397957
Epoch: 8, Loss: 0.06719586253166199
Epoch: 8, Loss: 0.07952744513750076
Epoch: 8, Loss: 0.09299949556589127
Epoch: 8, Loss: 0.09439953416585922
Epoch: 8, Loss: 0.14823561906814575
Epoch: 8, Loss: 0.18249595165252686
Epoch: 8, Loss: 0.096685990691185
Epoch: 8, Loss: 0.18649649620056152
Epoch: 8, Loss: 0.10783862322568893
Epoch: 9, Loss: 0.16869860887527466
Epoch: 9, Loss: 0.10015352815389633
Epoch: 9, Loss: 0.0884881466627121
Epoch: 9, Loss: 0.12254483997821808
Epoch: 9, Loss: 0.10206092894077301
Epoch: 9, Loss: 0.12178703397512436
Epoch: 9, Loss: 0.08750816434621811
Epoch: 9, Loss: 0.06052668020129204
Epoch: 9, Loss: 0.08867156505584717
Epoch: 9, Loss: 0.0974321961402893
Epoch: 9, Loss: 0.0959152951836586
Epoch: 9, Loss: 0.07564526051282883
Epoch: 9, Loss: 0.11219245940446854
Epoch: 9, Loss: 0.1046534851193428
Epoch: 9, Loss: 0.1300579011440277
Epoch: 10, Loss: 0.11665936559438705
Epoch: 10, Loss: 0.06504973769187927
Epoch: 10, Loss: 0.08407012373209
Epoch: 10, Loss: 0.05096640810370445
Epoch: 10, Loss: 0.07990407198667526
Epoch: 10, Loss: 0.07926628738641739
Epoch: 10, Loss: 0.07281254231929779
Epoch: 10, Loss: 0.11017313599586487
Epoch: 10, Loss: 0.05227038636803627
Epoch: 10, Loss: 0.05443471670150757
Epoch: 10, Loss: 0.15636731684207916
Epoch: 10, Loss: 0.15815816819667816
Epoch: 10, Loss: 0.21110261976718903
Epoch: 10, Loss: 0.09130672365427017
Epoch: 10, Loss: 0.09946274012327194
Epoch: 11, Loss: 0.057944249361753464
Epoch: 11, Loss: 0.09726879000663757
Epoch: 11, Loss: 0.10303287953138351
Epoch: 11, Loss: 0.09781133383512497
Epoch: 11, Loss: 0.19089098274707794
Epoch: 11, Loss: 0.12198926508426666
Epoch: 11, Loss: 0.057903505861759186
Epoch: 11, Loss: 0.04564572870731354
Epoch: 11, Loss: 0.08464548736810684
Epoch: 11, Loss: 0.13230940699577332
Epoch: 11, Loss: 0.06634499877691269
Epoch: 11, Loss: 0.1169382855296135
Epoch: 11, Loss: 0.0822979286313057
Epoch: 11, Loss: 0.10329145938158035
Epoch: 11, Loss: 0.04347347468137741
Epoch: 12, Loss: 0.14635439217090607
Epoch: 12, Loss: 0.0657786950469017
Epoch: 12, Loss: 0.08434062451124191
Epoch: 12, Loss: 0.20475395023822784
Epoch: 12, Loss: 0.0925668478012085
Epoch: 12, Loss: 0.07810705900192261
Epoch: 12, Loss: 0.06309815496206284
Epoch: 12, Loss: 0.03942534700036049
Epoch: 12, Loss: 0.08672000467777252
Epoch: 12, Loss: 0.15330499410629272
Epoch: 12, Loss: 0.03887832164764404
Epoch: 12, Loss: 0.0620306022465229
Epoch: 12, Loss: 0.08075906336307526
Epoch: 12, Loss: 0.07028231024742126
Epoch: 12, Loss: 0.31318947672843933
Epoch: 13, Loss: 0.08207697421312332
Epoch: 13, Loss: 0.08227112144231796
Epoch: 13, Loss: 0.25032734870910645
Epoch: 13, Loss: 0.04769178479909897
Epoch: 13, Loss: 0.08373039215803146
Epoch: 13, Loss: 0.06612466275691986
Epoch: 13, Loss: 0.11040417104959488
Epoch: 13, Loss: 0.102576345205307
Epoch: 13, Loss: 0.057252656668424606
Epoch: 13, Loss: 0.05522434040904045
Epoch: 13, Loss: 0.1900145411491394
Epoch: 13, Loss: 0.031616296619176865
Epoch: 13, Loss: 0.07343316823244095
Epoch: 13, Loss: 0.05591113120317459
Epoch: 13, Loss: 0.08399756252765656
Epoch: 14, Loss: 0.05585789680480957
Epoch: 14, Loss: 0.17621572315692902
Epoch: 14, Loss: 0.12539879977703094
Epoch: 14, Loss: 0.1497756689786911
Epoch: 14, Loss: 0.09994478523731232
Epoch: 14, Loss: 0.0944785475730896
Epoch: 14, Loss: 0.08723460137844086
Epoch: 14, Loss: 0.04545479267835617
Epoch: 14, Loss: 0.08805491775274277
Epoch: 14, Loss: 0.06315603852272034
Epoch: 14, Loss: 0.05159417912364006
Epoch: 14, Loss: 0.10094490647315979
Epoch: 14, Loss: 0.07027286291122437
Epoch: 14, Loss: 0.0470895990729332
Epoch: 14, Loss: 0.11028102785348892
Epoch: 15, Loss: 0.045060642063617706
Epoch: 15, Loss: 0.04938020557165146
Epoch: 15, Loss: 0.06834837794303894
Epoch: 15, Loss: 0.15616868436336517
Epoch: 15, Loss: 0.15541358292102814
Epoch: 15, Loss: 0.09766335040330887
Epoch: 15, Loss: 0.09333530068397522
Epoch: 15, Loss: 0.07370088994503021
Epoch: 15, Loss: 0.06582918763160706
Epoch: 15, Loss: 0.05520294979214668
Epoch: 15, Loss: 0.10794348269701004
Epoch: 15, Loss: 0.08371387422084808
Epoch: 15, Loss: 0.08264230191707611
Epoch: 15, Loss: 0.12044091522693634
Epoch: 15, Loss: 0.007034500129520893
Epoch: 16, Loss: 0.08228421956300735
Epoch: 16, Loss: 0.055956728756427765
Epoch: 16, Loss: 0.043507058173418045
Epoch: 16, Loss: 0.06599722057580948
Epoch: 16, Loss: 0.2897316515445709
Epoch: 16, Loss: 0.09847339987754822
Epoch: 16, Loss: 0.07011859863996506
Epoch: 16, Loss: 0.05918389558792114
Epoch: 16, Loss: 0.13428588211536407
Epoch: 16, Loss: 0.07952065765857697
Epoch: 16, Loss: 0.04719313979148865
Epoch: 16, Loss: 0.04923398047685623
Epoch: 16, Loss: 0.0654115378856659
Epoch: 16, Loss: 0.08415935188531876
Epoch: 16, Loss: 0.05341716483235359
Epoch: 17, Loss: 0.1475532054901123
Epoch: 17, Loss: 0.02024553157389164
Epoch: 17, Loss: 0.07284535467624664
Epoch: 17, Loss: 0.0754370391368866
Epoch: 17, Loss: 0.11213703453540802
Epoch: 17, Loss: 0.15643589198589325
Epoch: 17, Loss: 0.07160573452711105
Epoch: 17, Loss: 0.19046425819396973
Epoch: 17, Loss: 0.07619020342826843
Epoch: 17, Loss: 0.09263564646244049
Epoch: 17, Loss: 0.06915563344955444
Epoch: 17, Loss: 0.01156489085406065
Epoch: 17, Loss: 0.06512542814016342
Epoch: 17, Loss: 0.04621399939060211
Epoch: 17, Loss: 0.04422219842672348
Epoch: 18, Loss: 0.10038499534130096
Epoch: 18, Loss: 0.04607659578323364
Epoch: 18, Loss: 0.04968797042965889
Epoch: 18, Loss: 0.05779831483960152
Epoch: 18, Loss: 0.11100533604621887
Epoch: 18, Loss: 0.1073591560125351
Epoch: 18, Loss: 0.055142637342214584
Epoch: 18, Loss: 0.041302818804979324
Epoch: 18, Loss: 0.07055516541004181
Epoch: 18, Loss: 0.1296282261610031
Epoch: 18, Loss: 0.2507927715778351
Epoch: 18, Loss: 0.03145240619778633
Epoch: 18, Loss: 0.07658171653747559
Epoch: 18, Loss: 0.04979502037167549
Epoch: 18, Loss: 0.10179967433214188
Epoch: 19, Loss: 0.032172564417123795
Epoch: 19, Loss: 0.04599357023835182
Epoch: 19, Loss: 0.06585899740457535
Epoch: 19, Loss: 0.12835153937339783
Epoch: 19, Loss: 0.23286037147045135
Epoch: 19, Loss: 0.05755440145730972
Epoch: 19, Loss: 0.12222418934106827
Epoch: 19, Loss: 0.09233970940113068
Epoch: 19, Loss: 0.0381230004131794
Epoch: 19, Loss: 0.07520997524261475
Epoch: 19, Loss: 0.052109360694885254
Epoch: 19, Loss: 0.1275923103094101
Epoch: 19, Loss: 0.01719820499420166
Epoch: 19, Loss: 0.08386615663766861
Epoch: 19, Loss: 0.056785695254802704
Epoch: 20, Loss: 0.09864435344934464
Epoch: 20, Loss: 0.06563133746385574
Epoch: 20, Loss: 0.04906895384192467
Epoch: 20, Loss: 0.06592349708080292
Epoch: 20, Loss: 0.13757441937923431
Epoch: 20, Loss: 0.07727532088756561
Epoch: 20, Loss: 0.1268058866262436
Epoch: 20, Loss: 0.0438794307410717
Epoch: 20, Loss: 0.20032662153244019
Epoch: 20, Loss: 0.08311507105827332
Epoch: 20, Loss: 0.03291914612054825
Epoch: 20, Loss: 0.03319830447435379
Epoch: 20, Loss: 0.03908344730734825
Epoch: 20, Loss: 0.09202134609222412
Epoch: 20, Loss: 0.10754343122243881
Epoch: 21, Loss: 0.060767848044633865
Epoch: 21, Loss: 0.06006554514169693
Epoch: 21, Loss: 0.15094682574272156
Epoch: 21, Loss: 0.09112340956926346
Epoch: 21, Loss: 0.13275636732578278
Epoch: 21, Loss: 0.055200595408678055
Epoch: 21, Loss: 0.0775621086359024
Epoch: 21, Loss: 0.013896288350224495
Epoch: 21, Loss: 0.07224148511886597
Epoch: 21, Loss: 0.05744706094264984
Epoch: 21, Loss: 0.025953911244869232
Epoch: 21, Loss: 0.07248775660991669
Epoch: 21, Loss: 0.07357431948184967
Epoch: 21, Loss: 0.06783527880907059
Epoch: 21, Loss: 0.652998149394989
Epoch: 22, Loss: 0.09666144102811813
Epoch: 22, Loss: 0.04708953574299812
Epoch: 22, Loss: 0.18975655734539032
Epoch: 22, Loss: 0.02625039592385292
Epoch: 22, Loss: 0.057794664055109024
Epoch: 22, Loss: 0.042824387550354004
Epoch: 22, Loss: 0.14518345892429352
Epoch: 22, Loss: 0.06838375329971313
Epoch: 22, Loss: 0.04264985769987106
Epoch: 22, Loss: 0.10077853500843048
Epoch: 22, Loss: 0.1454738825559616
Epoch: 22, Loss: 0.0696866437792778
Epoch: 22, Loss: 0.046377506107091904
Epoch: 22, Loss: 0.060245536267757416
Epoch: 22, Loss: 0.043028052896261215
Epoch: 23, Loss: 0.058906134217977524
Epoch: 23, Loss: 0.03311148285865784
Epoch: 23, Loss: 0.06225239485502243
Epoch: 23, Loss: 0.07018955796957016
Epoch: 23, Loss: 0.10179737210273743
Epoch: 23, Loss: 0.10878556221723557
Epoch: 23, Loss: 0.084663987159729
Epoch: 23, Loss: 0.10377763956785202
Epoch: 23, Loss: 0.025411134585738182
Epoch: 23, Loss: 0.1869947910308838
Epoch: 23, Loss: 0.02894059382379055
Epoch: 23, Loss: 0.027495119720697403
Epoch: 23, Loss: 0.061604104936122894
Epoch: 23, Loss: 0.11345821619033813
Epoch: 23, Loss: 0.31026890873908997
Epoch: 24, Loss: 0.09189581125974655
Epoch: 24, Loss: 0.06119988113641739
Epoch: 24, Loss: 0.04413153976202011
Epoch: 24, Loss: 0.041417546570301056
Epoch: 24, Loss: 0.11074061691761017
Epoch: 24, Loss: 0.040404997766017914
Epoch: 24, Loss: 0.07503598183393478
Epoch: 24, Loss: 0.10617117583751678
Epoch: 24, Loss: 0.22231313586235046
Epoch: 24, Loss: 0.07838433235883713
Epoch: 24, Loss: 0.08499585092067719
Epoch: 24, Loss: 0.05935094133019447
Epoch: 24, Loss: 0.05561701953411102
Epoch: 24, Loss: 0.049859460443258286
Epoch: 24, Loss: 0.03080826811492443
Epoch: 25, Loss: 0.062089405953884125
Epoch: 25, Loss: 0.11244133859872818
Epoch: 25, Loss: 0.036461398005485535
Epoch: 25, Loss: 0.03772846609354019
Epoch: 25, Loss: 0.04399564117193222
Epoch: 25, Loss: 0.08478277921676636
Epoch: 25, Loss: 0.2535116672515869
Epoch: 25, Loss: 0.102987140417099
Epoch: 25, Loss: 0.060769859701395035
Epoch: 25, Loss: 0.058526553213596344
Epoch: 25, Loss: 0.13362768292427063
Epoch: 25, Loss: 0.021375728771090508
Epoch: 25, Loss: 0.03756783902645111
Epoch: 25, Loss: 0.056030597537755966
Epoch: 25, Loss: 0.06840338557958603

In [ ]:
# model evaluation
with torch.no_grad():
  for batch_features, batch_labels in test_loader:
   # Ensure X_test_tensor is float32 for consistency with model weights
   X_test_tensor_f32 = X_test_tensor.float()
   y_pred = model.forward(batch_features.float())
   y_pred = (y_pred > 0.9).float()
   # Ensure y_test_tensor is float32 for comparison
   accuracy = (y_pred == batch_labels).float().mean()
   print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.55859375
Accuracy: 0.55859375
Accuracy: 0.58203125
Accuracy: 0.5740740895271301